version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
    environment:
      - NODE_ENV=development
      - PORT=5001
      - MONGO_URI=mongodb://mongodb:27017/api-boilerplate
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_ACCESS_SECRET=your_docker_access_secret
      - JWT_REFRESH_SECRET=your_docker_refresh_secret
      - JWT_ACCESS_EXPIRES_IN=15m
      - JWT_REFRESH_EXPIRES_IN=7d
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX=100
      - CLIENT_URL=http://localhost:3000
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./logs:/usr/src/app/logs

  mongodb:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
